language: go
go:
- 1.14.x
env:
  global:
  - GO111MODULE=on
  - secure: P5Z9AteX+QPxirj4XGbTt9zOgENevx6s+aDKcCpQDQm7qx28tnp4YTlbeLCSupwxpwg/IcaUk9mz2MWbquMnt8IQM1KlDN7YZsTfkIG553puDBsW3lMLx85whTliihbdRSklj9tRIoLgthQrtcc+9hv48oCbDVYNU3hiN4bMFa+RthYON9UDnSYMNN9U4fm/XUNQHYctwLCVRChDd33r6q8MN9Kt9TkjHagqWqmx7DaqMJn6aWUqD5OT08AV/ZuigA/A5IK94ho8jaHOAHnPKO2Y/vTU4KLI1pJdpmNtgt4b0VNlRFoQ+c36Eo1crQqu998N/fnbfFzXHPR8M0lNpuhoiwmjwNEvKHZSwQjxpyu8Z0mviMmmYzlGOXc5Q1a+jjoOHvNBY3vRnb8mB8r9NPKQgbG30nVKbXBAHRJn/VShjibRBFIK8c08g/U7sNHggkPW4/esMcPL+gAB1JqzsPKs+U2b1UAuqiIRtw+vWTBjcbR5HbmNdz+hlM6wfyLmirzaVshIU/vHOSbp+YpaIQpoIDZqM+6bm63FMXz7nnLxQtf0WLpBZlN2m/JZ5jqxCxuBMt7EqxyeCmxovrnWpYOua5sKnkDjI/YLa4Kb76k6An28dWH12HNh2URnpPxSYyTWzYr/IAIu4QL63R+EChAMmocg7AyKxnbObAcC2S0=
  - secure: OHg/yJX0IFA7hgA3Jfz26xDoahmKm5jh9qsZtwITLVzRPjKSHiScosJ6g02MXqOgSULCYRiaL6ukTAAiJijTxcPsO3Wj9ciVb6HBwN7yrnRj2j/Q8kjaD8roLsR5g0skBJaL4nm5d/uYfvtbq7SWPOk1YafkD6KweCDjHi2q7dlHvT6Ur4TuvO1+M+KbuhmJUg/MoKDWOVSj5xesNoXI2A62bacvdia7y5WDrgImQ9A9fBYxcD8Mg7GaKPGuTYZ0me3Em8V8gAJWRMH0EZX40L2Wf1QVePJu3PsTZ/k/JxY1F54O4zxzolj62xALZR2sgjPibNfTaPhSt/T9N3Gz+qyVjk66FEqZVs92aNzqUVZCskh5/AqenUwKgusxBT2eQ7pxIVf9yzAjAcxtmeAyaIzTdoVNgY2TWMj3XTaYzlQTH1ZmftO+vsDMStMSRi+40KkWc0JdRWRxkExqPzB59ZDANAwOPqwiWv6zZcU2AqK4bPs4JUZFCwkYrz0ygHgULqh9hf2nUrq+bITCbScp4xj75KI5qwrjYtH/0k/7AK3/v+S4QnD3fYD1Yw8vKKcz7ImjEbUHRPC6lsRIgFd9eXjvCynvMfYWXKsYSDhYMIXJbj8ywdJrekVioJRDu39IHmXOXVrU1uo+P9TJ2NDNl7+LvaHXQ+NHWxOQsBsoXLM=
jobs:
  include:
  - stage: build
    install: []
    script:
    - set -e
    - scripts/ci scripts/build
    - scripts/ci scripts/test
    before_deploy: scripts/ci scripts/dist-all
    deploy:
      on:
        tags: true
      skip_cleanup: true
      file_glob: true
      provider: releases
      api_key:
        secure: QEChpHeRG89iU6Ig2SELNjptQkriM8zyOn5aX6+pNbfufMhxp5KR6PihCkbzE/Wx/k8PFM4+AZqiyXO6y16DWaJCKoQKlDKEst3yirEZ78/ajV2zD9kPR5d9nEVUst9Aeuhg2i8LIKsRl+5WOa3q0/3tYn37Flm5AoR86bDqcfSHCkc18OY8fY0HfL8JQNWPDrx/+pbqvUVh4nBo4Tvhp0Y5j+bn2wseb1u7c1m03iKy33qK8JRSn76kv0f8xzLRBBb4eoBR5CyN4jpha/76TJ0imQx1WjJYb2UYL9IwScMsr+la3VJo/OzTKUZRtsi6a77+kzD/nkQBcjhKVvbNil/Qjz0zMLUd2ltFn7kDOTWqIbfQjdzk4Yu+RTRK0KKNgZOxAZ8F3SblUbgUeoN7tI0IkCig7TRNgVzPWjYN6MN+m6PQkF7pHJoxjgnMFDg4wZbUh45HiR/YJ00uw0pLcSWg/aoSg4xbPn3tl8x/PAf1gPDalP0A6f1bCOGAh7YXDZOaBN6uYq9o88tAOiOCeKd781Hcz1tu9/EI70nbEqyZi4xfIdimfh/svSd27LlJtVsn437UDuls41MNjf/FTgyL4RGxIUPPsoX+8gXyU3cWDJOq20bxERvWVaeRgSmKNJ1C8wV+jjJ/KewnW8NwBt0eyM+ygoGwWhPKDiYWexk=
      file: bin/*
    after_deploy: scripts/ci scripts/run-workflow
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    template:
    - "<%{compare_url}|%{commit_subject}> | %{author}"
    - "%{repository_slug} %{branch} | <%{build_url}|#%{build_number}> %{result} in
      %{elapsed_time}"
    rooms:
    - secure: zu/MZURvDivl7qapoRAcOtF6yH9zUwr1YqpDObAlF9mAO0z5VllKVVdDZJZ6QwGNzfl5m4MBXLh7PzXex3VXwbXlGYvUbsvUj9cLo2cLqJqtgBQ4DuVVCJXF4Rj/8sNRx4JfquKGE/Yae07MUXdcIJ1FuOoVHpUTNW1eA0SE5LIWRB8WJiBC53jl5itkUOUqh5l43W+8djpDbcds+vyjE9omwuHW2Zxh7TGqXBSCf2LPmjAzL4eZD2yTE8VUNNbKwx6dBGqpS0Y3Ke4R4bvj9PAZUAqG3dxMKUKU0OyJHg/Jkg5ZqVEoghCSZNGpD2aEfB7C5+hWF1A6Ftvs09qd3cGyioSD88Hj7F7hCzgz2Z+rBMmhvXb9cEeX3iDBDMQ+xd7bDL8bmYMSTVFnnqqz+4SewRCo3efbEF9xaBkUfIpal1Ax0XL9PnBHCniKqVkL99v9ERE5maUoD8W/7JwamqG+ija7P2kblNNLB6G+mh75KHmKU5GNB2+QcLtk3WUtxKLP9KqCUc7CZ9pk02nQlkXClG2nbAWo0QyYq1opbjDMmCpLK1FZiPJpL82QleXfw2JuKIVuUfq9bihOwc1AJvJhJDtNTDQMp+j+2kHBwQOy/EXd1HkK4JTt84+JXzurK3UhcH39g03TCvTpDq/dHy69a706OK4CW2kxIyIfO08=
